// Mobile-only enhancement shared by the Worker page and the Pages build.
export function mobilePage(page) {
  return page.replace('V1.06', 'V1.07').replace('</head>', `<style>
.mobileOnly{display:none}
@media(max-width:580px){
.head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;margin-bottom:12px}.head .brand{gap:8px;min-width:0}.head .logo{width:36px;height:36px;border-radius:10px}.head .brand h1{font-size:17px;line-height:1.3;letter-spacing:-.04em}.head .brand p{display:none}.mobileOnly{display:block}.desktopTitle{display:none}.mobileCreator{font-size:10px;color:#66758a;margin-top:4px;white-space:nowrap}.head .headActions{display:none}.mobileHeadTools{display:flex;gap:7px;align-items:center}.mobileUpdate{text-align:right;font-size:10px;line-height:1.4;color:#657184}.mobileUpdate b{display:block;color:#31405b}.mobileContact{border:1px solid #dbe1e9;border-radius:10px;background:#fff;color:#263249;padding:8px 5px;min-height:44px;font-size:11px;font-weight:800}.sidebar{display:block}.panel{padding:12px}.tabs{margin-bottom:10px}.platformTitle{font-size:12px}.mobileSummary{display:flex;gap:8px;align-items:center}.mobileSummary span{flex:1;min-width:0;font-size:12px;line-height:1.5;color:#506078}.mobileSummary button{border:0;background:#152033;color:#fff;border-radius:10px;min-height:44px;padding:9px 14px;font-size:14px;font-weight:800}.mobileSheetOverlay{position:fixed;inset:0;z-index:40;background:#15203380;display:flex;align-items:flex-end}.mobileSheet{width:100%;max-height:88dvh;max-height:88vh;background:#fff;border-radius:22px 22px 0 0;display:flex;flex-direction:column;box-shadow:0 -15px 50px #15203330}.mobileSheetHead{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid #edf0f5}.mobileSheetHead h2{margin:0;font-size:19px}.mobileSheetHead button{width:44px;height:44px;border:0;border-radius:10px;font-size:24px;background:#eef2f6}.mobileSheetBody{overflow:auto;overscroll-behavior:contain;padding:16px 18px}.mobileSheetBody .field{margin-bottom:16px}.mobileSheetBody .pill,.mobileSheetBody .segment button{min-height:44px}.mobileSheetBody .mapPanel{margin-top:16px}.mobileSheetFooter{display:flex;gap:10px;padding:12px 18px max(12px,env(safe-area-inset-bottom));border-top:1px solid #edf0f5}.mobileSheetFooter button{border:1px solid #dbe1e9;border-radius:10px;min-height:44px;font-weight:800;background:#fff;padding:10px 18px}.mobileSheetFooter .apply{flex:1;background:#152033;color:#fff;border-color:#152033}.mobileMenu{position:absolute;right:12px;top:76px;z-index:45;width:220px;padding:8px;background:#fff;border:1px solid #dbe1e9;border-radius:14px;box-shadow:0 10px 30px #15203325}.mobileMenu button{display:block;width:100%;text-align:left;min-height:44px;border:0;background:#fff;border-radius:9px;padding:10px;color:#263249;font-weight:800}.mobileMenu p{font-size:11px;line-height:1.6;margin:8px;color:#657184}.mobileMapHidden{display:none}.main{padding:14px}.layout{gap:12px}.wrap{padding-top:12px}
}
@media(max-width:360px){.head .logo{width:30px;height:30px}.head .brand h1{font-size:15px}.mobileCreator{font-size:9px}.mobileHeadTools{gap:4px}.mobileContact{font-size:10px}.mobileUpdate{font-size:9px}}
</style></head>`).replace('</body>', `<script>
(()=>{
const mobile=matchMedia('(max-width:580px)'),panel=q('.panel'),sidebar=q('.sidebar'),controls=q('.controls'),filter=q('#filters'),reload=q('#reload'),map=q('#regionMap');
const h=q('.brand h1');h.innerHTML='<span class="desktopTitle">外送優惠券查詢</span><span class="mobileOnly">臺灣外送優惠券查詢</span>';
h.parentElement.insertAdjacentHTML('beforeend','<div class="mobileOnly mobileCreator">製作人：EVS-ZHAO TECH©</div>');
q('.head').insertAdjacentHTML('beforeend','<div class="mobileOnly mobileHeadTools"><div class="mobileUpdate"><b>V1.07 · 更新</b><span id="mobileUpdated">讀取中</span></div><button class="mobileContact" id="mobileContact" aria-expanded="false" aria-controls="mobileMenu">聯絡我們</button></div>');
panel.insertAdjacentHTML('beforeend','<div class="mobileOnly mobileSummary"><span id="mobileSummary"></span><button id="openFilters" aria-haspopup="dialog">篩選</button></div>');
document.body.insertAdjacentHTML('beforeend','<div id="mobileMenu" class="mobileOnly mobileMenu hidden"><button data-contact="contact">聯絡我們／LINE QR Code</button><button data-contact="report">回報問題</button><button id="mobileReload">重新讀取優惠資料</button><p id="mobileFullDate"></p></div><div id="mobileOverlay" class="mobileOnly mobileSheetOverlay hidden"><section class="mobileSheet" role="dialog" aria-modal="true" aria-labelledby="mobileSheetTitle"><header class="mobileSheetHead"><h2 id="mobileSheetTitle">篩選優惠券</h2><button id="closeFilters" aria-label="關閉篩選">×</button></header><div class="mobileSheetBody" id="mobileSheetBody"></div><footer class="mobileSheetFooter"><button id="resetFilters">重設</button><button class="apply" id="applyFilters">套用篩選</button></footer></section></div>');
const overlay=q('#mobileOverlay'),body=q('#mobileSheetBody'),menu=q('#mobileMenu');let draft=null,oldOverflow='';
const originalLoad=load,originalRender=render;
function summary(){const names={all:'全部分類',general:'全區通用',region:'限定地區',store:'限定店家',grocery:'生鮮超市',takeout:'外帶自取'};q('#mobileSummary').textContent=q('#region').value+' · '+(isNew==='all'?'全部用戶':isNew==='true'?'新用戶':'舊用戶')+' · '+names[category];}
render=function(){if(!draft)originalRender();summary()};
load=async function(){if(draft)return;await originalLoad();summary()};
function syncIdentity(){document.querySelectorAll('[data-user]').forEach(x=>{x.classList.toggle('on',x.dataset.user===isNew);x.setAttribute('aria-pressed',String(x.dataset.user===isNew))});syncMap();filters();summary()}
function closeSheet(cancel=true){if(!draft)return;const saved=draft;draft=null;if(cancel){q('#region').value=saved.region;isNew=saved.user;shown=new Set(saved.shown);category=saved.category;located=saved.located;syncIdentity()}overlay.classList.add('hidden');document.body.style.overflow=oldOverflow;q('#openFilters').focus()}
q('#openFilters').onclick=()=>{draft={region:q('#region').value,user:isNew,shown:[...shown],category,located};oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';overlay.classList.remove('hidden');q('#closeFilters').focus()};
q('#closeFilters').onclick=()=>closeSheet();overlay.onclick=ev=>{if(ev.target===overlay)closeSheet()};
q('#resetFilters').onclick=()=>{isNew='all';shown=new Set(['code','link']);category='all';syncIdentity()};
q('#applyFilters').onclick=async()=>{const changed=draft&&(draft.region!==q('#region').value||draft.user!==isNew),keepShown=new Set(shown),keepCategory=category;closeSheet(false);if(changed)await load();shown=keepShown;category=keepCategory;filters();render()};
function toggleMenu(open){menu.classList.toggle('hidden',!open);q('#mobileContact').setAttribute('aria-expanded',String(open))}
q('#mobileContact').onclick=()=>toggleMenu(menu.classList.contains('hidden'));
menu.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>{toggleMenu(false);const report=b.dataset.contact==='report';q('#contactTitle').textContent=report?'回報問題':'聯絡我們';q('#contactText').textContent=report?'請使用 LINE 掃描 QR Code，傳送問題描述與畫面截圖。':'使用 LINE 掃描 QR Code 即可聯絡我們。';q('#contactModal').classList.remove('hidden')});
q('#mobileReload').onclick=()=>{toggleMenu(false);load()};document.addEventListener('click',ev=>{if(!menu.contains(ev.target)&&ev.target!==q('#mobileContact'))toggleMenu(false)});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){closeSheet();toggleMenu(false)}if(ev.key==='Tab'&&!overlay.classList.contains('hidden')){const a=[...overlay.querySelectorAll('button,select,[tabindex="0"]')].filter(x=>x.getClientRects().length&&!x.disabled);if(ev.shiftKey&&document.activeElement===a[0]){ev.preventDefault();a.at(-1).focus()}else if(!ev.shiftKey&&document.activeElement===a.at(-1)){ev.preventDefault();a[0].focus()}}});
const oldMapOpen=q('#mapOpen').onclick;q('#mapOpen').onclick=()=>{if(mobile.matches){map.classList.toggle('mobileMapHidden');if(!map.classList.contains('mobileMapHidden'))map.scrollIntoView({behavior:'smooth',block:'nearest'})}else oldMapOpen()};
function responsive(){if(mobile.matches){body.append(controls,filter,map);reload.style.display='none';map.classList.add('mobileMapHidden')}else{closeSheet();panel.insertBefore(controls,reload);panel.insertBefore(filter,reload);sidebar.append(map);reload.style.display='';map.classList.remove('mobileMapHidden');toggleMenu(false)}}
mobile.addEventListener('change',responsive);responsive();summary();
function updateDate(){const value=q('#updated').textContent;const m=value.match(/(\\d{4})[-/](\\d{2})[-/](\\d{2}).*?(\\d{2}:\\d{2})/);q('#mobileUpdated').innerHTML=m?m[2]+'/'+m[3]+'<br>'+m[4]:e(value);q('#mobileFullDate').textContent='V1.07 · 更新日期：'+value}
new MutationObserver(updateDate).observe(q('#updated'),{childList:true,characterData:true,subtree:true});updateDate();
})();
</script></body>`);
}
